// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}}
];
